server:
  port: 9000

spring:
  application:
    name: mytrip-web-gateway

#Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka

#Details which needs to be striped in Gateway. By default all the header informations will be blocked in Gateway.
zuul: 
  routes:
    mytrip-authentication-service:
      sensitive-headers: 