server:
  port: 9000

spring:
  application:
    name: zuul-server

#Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka

#ZUUL Configuration
zuul:
  prefix: /api
  routes:
    flight-fare-service:
      path: /flight-fare-service/**
      service-id: FLIGHT-FARE-SERVICE
    support-service:
      path: /support-service/**
      url: http://localhost:8092
      service-id: SUPPORT-SERVICE
    flight-search-service:
      path: /flight-search-service/**
      service-id: FLIGHT-SEARCH-SERVICE
    static:
      path: /static/**